-- Fichier de données de base (Seed)
-- Généré à partir de l'inventaire fourni par l'utilisateur

DROP TABLE IF EXISTS products;

CREATE TABLE products (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    category TEXT,
    brand TEXT,
    model TEXT,
    state TEXT,
    stock INTEGER DEFAULT 0,
    purchase_price REAL,
    sale_price REAL,
    min_sale_price REAL,
    entry_date TEXT,
    cpu TEXT,
    ram TEXT,
    gpu TEXT,
    storage TEXT,
    min_stock INTEGER DEFAULT 2,
    is_deleted INTEGER DEFAULT 0,
    remarque TEXT,
    UNIQUE(category, brand, model, state)
);

-- Insertion des données
INSERT OR IGNORE INTO products (category, brand, model, state, stock, sale_price, min_sale_price) VALUES 
('Laptops', 'Laptop Fujitsu', '', 'Occasion', 0 , 0.0, 0.0),
('Laptops', 'Laptop HP', '', 'Occasion', 1 , 0.0, 0.0),
('Laptops', 'Laptop Asus', '', 'Occasion', 1 , 0.0, 0.0),
('Laptops', 'Apple Macbook', '2015', 'Occasion', 1 , 0.0, 0.0),
('Laptops', 'Mini Desktop', '', 'Occasion', 1 , 0.0, 0.0),
('Laptops', 'Vidéoprojecteur', '', 'Occasion', 1 , 0.0, 0.0),
('Laptops', 'Desktop', '', 'Occasion', 0 , 0.0, 0.0),
('Laptops', 'Laptop Dell', '14 pouces', 'Occasion', 4 , 0.0, 0.0),
('Laptops', 'Apple Macbook', '2017 - 13,3 pouces', 'Occasion', 8 , 0.0, 0.0),
('Laptops', 'Apple Macbook', '2020 - 13,3 pouces', 'Occasion', 1 , 0.0, 0.0),
('Laptops', 'Laptop Medion', '15 pouces', 'Occasion', 1 , 0.0, 0.0),
('Laptops', 'Laptop Dell', '15 pouces', 'Occasion', 2 , 0.0, 0.0),
('Stockage', 'Disque Dur HDD', '120 Go', 'Neuf', 0 , 0.0, 0.0),
('Stockage', 'Disque Dur HDD', '250 Go', 'Neuf', 0 , 0.0, 0.0),
('Stockage', 'Disque Dur HDD', '320 Go', 'Neuf', 0 , 0.0, 0.0),
('Stockage', 'Disque Dur HDD', '500 Go', 'Neuf', 0 , 0.0, 0.0),
('Stockage', 'Disque Dur HDD', '1 To', 'Neuf', 0 , 0.0, 0.0),
('Stockage', 'Disque Dur M2', '128 Go', 'Neuf', 0 , 0.0, 0.0),
('Stockage', 'Disque Dur M2', '256 Go', 'Neuf', 0 , 0.0, 0.0),
('Stockage', 'Disque Dur M2', '512 Go', 'Neuf', 0 , 0.0, 0.0),
('Stockage', 'SSD 2.5"', '120 Go', 'Neuf', 0 , 0.0, 0.0),
('Stockage', 'SSD 2.5"', '256 Go', 'Neuf', 0 , 0.0, 0.0),
('Stockage', 'SSD 2.5"', '512 Go', 'Neuf', 0 , 0.0, 0.0),
('Stockage', 'SSD 2.5"', '1 To', 'Neuf', 0 , 0.0, 0.0),
('Stockage', 'RAM Laptop PC4', '4 Go', 'Occasion', 0 , 0.0, 0.0),
('Stockage', 'RAM Laptop PC4', '8 Go', 'Occasion', 0 , 0.0, 0.0),
('Stockage', 'RAM Laptop PC4', '16 Go', 'Occasion', 0 , 0.0, 0.0),
('Stockage', 'RAM Laptop PC3', '4 Go', 'Occasion', 0 , 0.0, 0.0),
('Stockage', 'RAM Laptop PC3', '8 Go', 'Occasion', 0 , 0.0, 0.0),
('Stockage', 'RAM Laptop PC3', '16 Go', 'Occasion', 0 , 0.0, 0.0),
('Stockage', 'RAM Desktop PC3', '4 Go', 'Occasion', 0 , 0.0, 0.0),
('Stockage', 'RAM Desktop PC3', '8 Go', 'Occasion', 0 , 0.0, 0.0),
('Stockage', 'RAM Desktop PC3', '16 Go', 'Occasion', 0 , 0.0, 0.0),
('Stockage', 'RAM Desktop PC4', '4 Go', 'Occasion', 0 , 0.0, 0.0),
('Stockage', 'RAM Desktop PC4', '8 Go', 'Occasion', 0 , 0.0, 0.0),
('Stockage', 'RAM Desktop PC4', '16 Go', 'Occasion', 0 , 0.0, 0.0),
('Stockage', 'Clé USB', '2 Go', 'Neuf', 0 , 0.0, 0.0),
('Stockage', 'Clé USB', '4 Go', 'Neuf', 2 , 0.0, 0.0),
('Stockage', 'Clé USB', '8 Go', 'Neuf', 4 , 0.0, 0.0),
('Stockage', 'Clé USB', '16 Go', 'Neuf', 2 , 0.0, 0.0),
('Stockage', 'Clé USB', '32 Go', 'Neuf', 3 , 0.0, 0.0),
('Stockage', 'Clé USB', '64 Go', 'Neuf', 3 , 0.0, 0.0),
('Informatique', 'Mini Clavier', '', 'Neuf', 1 , 0.0, 0.0),
('Informatique', 'Clavier Flexible', '', 'Neuf', 3 , 0.0, 0.0),
('Informatique', 'Clavier d''occasion', '', 'Occasion', 6 , 0.0, 0.0),
('Informatique', 'Souris Bluetooth', '', 'Neuf', 9 , 0.0, 0.0),
('Informatique', 'Souris Brocante', '', 'Occasion', 6 , 0.0, 0.0),
('Informatique', 'Souris Vrac', '', 'Occasion', 3 , 0.0, 0.0),
('Informatique', 'Souris Neuve', 'HP', 'Neuf', 2 , 0.0, 0.0),
('Informatique', 'Souris Neuve', 'Lenovo', 'Neuf', 1 , 0.0, 0.0),
('Informatique', 'Souris Gaming', '', 'Neuf', 1 , 0.0, 0.0),
('Informatique', 'Support Laptop', '', 'Neuf', 10 , 0.0, 0.0),
('Informatique', 'Webcam', '', 'Neuf', 0 , 0.0, 0.0),
('Informatique', 'Connecteur RJ45', '', 'Neuf', 77 , 0.0, 0.0),
('Informatique', 'Boitier Disque Dur', '2.0', 'Neuf', 1 , 0.0, 0.0),
('Informatique', 'Boitier Disque Dur', '3.0', 'Neuf', 2 , 0.0, 0.0),
('Informatique', 'Clé WiFi', 'USB Internet', 'Neuf', 1 , 0.0, 0.0),
('Informatique', 'Clé WiFi', 'Avec antenne', 'Neuf', 1 , 0.0, 0.0),
('Informatique', 'Testeur de câble', 'Réseau', 'Neuf', 0 , 0.0, 0.0),
('Informatique', 'Adaptateur USB Réseau', '', 'Neuf', 1 , 0.0, 0.0),
('Informatique', 'Protection Clavier', '', 'Neuf', 1 , 0.0, 0.0),
('Informatique', 'Manchons', '', 'Neuf', 46 , 0.0, 0.0),
('Informatique', 'Carte Graphique', '', 'Occasion', 4 , 0.0, 0.0),
('Informatique', 'Glasse téléphone', '', 'Neuf', 20 , 0.0, 0.0),
('Moniteurs', 'Moniteur', '17 pouces', 'Occasion', 4 , 0.0, 0.0),
('Moniteurs', 'Moniteur', '19 pouces', 'Occasion', 0 , 0.0, 0.0),
('Moniteurs', 'Moniteur', '24 pouces', 'Occasion', 2 , 0.0, 0.0),
('Moniteurs', 'Moniteur', '24 pouces sans bordures', 'Neuf', 2 , 0.0, 0.0),
('Chargeurs PC', 'Chargeur Dell', 'Petit Bout', 'Occasion', 0 , 0.0, 0.0),
('Chargeurs PC', 'Chargeur Dell', 'Gros Bout', 'Occasion', 0 , 0.0, 0.0),
('Chargeurs PC', 'Chargeur Dell', 'Type-C', 'Neuf', 0 , 0.0, 0.0),
('Chargeurs PC', 'Chargeur Dell', 'GB 6A et 9A', 'Occasion', 3 , 0.0, 0.0),
('Chargeurs PC', 'Chargeur Dell', 'GB 5A et 4A', 'Occasion', 5 , 0.0, 0.0),
('Chargeurs PC', 'Chargeur Dell', 'PB', 'Occasion', 4 , 0.0, 0.0),
('Chargeurs PC', 'Chargeur Dell', 'USB', 'Occasion', 10 , 0.0, 0.0),
('Chargeurs PC', 'Chargeur Lenovo', 'Bout carré', 'Occasion', 0 , 0.0, 0.0),
('Chargeurs PC', 'Chargeur Lenovo', 'Type-C', 'Neuf', 0 , 0.0, 0.0),
('Chargeurs PC', 'Chargeur Lenovo', 'BC', 'Occasion', 4 , 0.0, 0.0),
('Chargeurs PC', 'Chargeur Lenovo', 'BR', 'Occasion', 4 , 0.0, 0.0),
('Chargeurs PC', 'Chargeur Lenovo', 'PB', 'Occasion', 2 , 0.0, 0.0),
('Chargeurs PC', 'Chargeur HP', 'Gros Bout', 'Occasion', 0 , 0.0, 0.0),
('Chargeurs PC', 'Chargeur HP', 'Bout bleu', 'Occasion', 8 , 0.0, 0.0),
('Chargeurs PC', 'Chargeur HP', 'GB 6 et 9A', 'Occasion', 2 , 0.0, 0.0),
('Chargeurs PC', 'Chargeur HP', 'BB 6 et 9A', 'Occasion', 0 , 0.0, 0.0),
('Chargeurs PC', 'Chargeur Acer', 'Petit Bout', 'Occasion', 3 , 0.0, 0.0),
('Chargeurs PC', 'Chargeur Acer', 'Normal', 'Occasion', 3 , 0.0, 0.0),
('Chargeurs PC', 'Chargeur Asus', 'Petit Bout', 'Occasion', 3 , 0.0, 0.0),
('Chargeurs PC', 'Chargeur Toshiba', '', 'Occasion', 7 , 0.0, 0.0),
('Chargeurs PC', 'Chargeur Samsung', '', 'Occasion', 2 , 0.0, 0.0),
('Chargeurs PC', 'Chargeur Sony', '', 'Occasion', 2 , 0.0, 0.0),
('Chargeurs PC', 'Chargeur Surface Pro', '', 'Occasion', 1 , 0.0, 0.0),
('Chargeurs PC', 'Chargeur 12V', '', 'Neuf', 4 , 0.0, 0.0),
('Chargeurs PC', 'Chargeur 9V', '', 'Neuf', 0 , 0.0, 0.0),
('Chargeurs PC', 'Chargeur 5V', '', 'Neuf', 0 , 0.0, 0.0),
('Chargeurs Tel', 'Chargeur Xiaomi', '120W', 'Neuf', 3 , 0.0, 0.0),
('Chargeurs Tel', 'Chargeur Xiaomi', '160W', 'Neuf', 2 , 0.0, 0.0),
('Chargeurs Tel', 'Chargeur Huawei', '88W', 'Neuf', 1 , 0.0, 0.0),
('Chargeurs Tel', 'Chargeur Huawei', '88W (vrac)', 'Neuf', 1 , 0.0, 0.0),
('Chargeurs Tel', 'Chargeur 5G', '88W', 'Neuf', 1 , 0.0, 0.0),
('Chargeurs Tel', 'Chargeur PB', '', 'Neuf', 1 , 0.0, 0.0),
('Chargeurs Tel', 'Chargeur Canal+', '', 'Neuf', 0 , 0.0, 0.0),
('Chargeurs Tel', 'Chargeur Oraimo Fast', 'Type-C', 'Neuf', 5 , 0.0, 0.0),
('Chargeurs Tel', 'Chargeur Oraimo Fast', 'iPhone', 'Neuf', 3 , 0.0, 0.0),
('Chargeurs Tel', 'Chargeur Oraimo Fast', 'Android', 'Neuf', 4 , 0.0, 0.0),
('Câbles & Vidéo', 'Câble HDMI', '1,5m', 'Neuf', 5 , 0.0, 0.0),
('Câbles & Vidéo', 'Câble HDMI', '3m', 'Neuf', 2 , 0.0, 0.0),
('Câbles & Vidéo', 'Câble HDMI', '5m', 'Neuf', 1 , 0.0, 0.0),
('Câbles & Vidéo', 'Câble VGA', '', 'Occasion', 9 , 0.0, 0.0),
('Câbles & Vidéo', 'Câble Display Port', '', 'Neuf', 2 , 0.0, 0.0),
('Câbles & Vidéo', 'Adaptateur Vidéo', 'HDMI vers VGA', 'Neuf', 4 , 0.0, 0.0),
('Câbles & Vidéo', 'Adaptateur Vidéo', 'VGA vers HDMI', 'Neuf', 2 , 0.0, 0.0),
('Câbles & Vidéo', 'Adaptateur Display Port', 'VGA', 'Neuf', 1 , 0.0, 0.0),
('Câbles & Vidéo', 'Adaptateur Display Port', 'HDMI', 'Neuf', 1 , 0.0, 0.0),
('Câbles & Vidéo', 'Adaptateur 3-en-1', 'Type-C/HDMI/USB', 'Neuf', 1 , 0.0, 0.0),
('Câbles & Vidéo', 'Adaptateur USB->HDMI', '', 'Neuf', 1 , 0.0, 0.0),
('Câbles & Vidéo', 'Adaptateur Simple', '', 'Neuf', 10 , 0.0, 0.0),
('Câbles & Vidéo', 'Câble Desktop', 'Original', 'Neuf', 6 , 0.0, 0.0),
('Câbles & Vidéo', 'Câble Laptop', 'Original', 'Neuf', 10 , 0.0, 0.0),
('Câbles & Vidéo', 'Câble Laptop', 'Copie', 'Neuf', 6 , 0.0, 0.0),
('Câbles & Vidéo', 'Câble Rallonge', '1,5m', 'Neuf', 10 , 0.0, 0.0),
('Câbles & Vidéo', 'Câble Rallonge', '3m', 'Neuf', 8 , 0.0, 0.0),
('Câbles & Vidéo', 'Câble Rallonge', '5m', 'Neuf', 2 , 0.0, 0.0),
('Câbles & Vidéo', 'Rallonge USB', '', 'Neuf', 1 , 0.0, 0.0),
('Câbles & Vidéo', 'Câble AV 2en1', 'Type 1', 'Neuf', 1 , 0.0, 0.0),
('Câbles & Vidéo', 'Câble AV 2en1', 'Type 2', 'Neuf', 2 , 0.0, 0.0),
('Câbles & Vidéo', 'Câble AV 2en1', 'Type 3', 'Neuf', 1 , 0.0, 0.0),
('Câbles & Vidéo', 'Câble AV 3en1', '', 'Neuf', 2 , 0.0, 0.0),
('Câbles & Vidéo', 'Câble ANI', '', 'Neuf', 1 , 0.0, 0.0),
('Câbles & Vidéo', 'Câble Radio', '', 'Neuf', 5 , 0.0, 0.0),
('Câbles & Vidéo', 'Câble Jaune-Noir Multifonction', '', 'Neuf', 5 , 0.0, 0.0),
('Câbles & Vidéo', 'Câble Réseau Sortir', '', 'Neuf', 2 , 0.0, 0.0),
('Câbles & Vidéo', 'Adaptateur OTG', 'Android', 'Neuf', 1 , 0.0, 0.0),
('Téléphonie', 'Power Bank', '10 000 mAh', 'Neuf', 1 , 0.0, 0.0),
('Téléphonie', 'Power Bank', '20 000 mAh', 'Neuf', 1 , 0.0, 0.0),
('Téléphonie', 'Cordon USB 2A', 'Type-C', 'Neuf', 3 , 0.0, 0.0),
('Téléphonie', 'Cordon USB 2A', 'Android', 'Neuf', 6 , 0.0, 0.0),
('Téléphonie', 'Cordon USB 2A', 'iPhone', 'Neuf', 5 , 0.0, 0.0),
('Téléphonie', 'Cordon Fast Charge', 'Type-C vers Type-C', 'Neuf', 6 , 0.0, 0.0),
('Téléphonie', 'Cordon Fast Charge', 'iPhone', 'Neuf', 4 , 0.0, 0.0),
('Téléphonie', 'Data Cable Art', '', 'Neuf', 1 , 0.0, 0.0),
('Audio', 'AirPods', '', 'Neuf', 0 , 0.0, 0.0),
('Audio', 'Écouteurs Oraimo', '', 'Neuf', 1 , 0.0, 0.0),
('Audio', 'Écouteurs iPhone', '', 'Neuf', 2 , 0.0, 0.0),
('Audio', 'Écouteurs Type-C', '', 'Neuf', 1 , 0.0, 0.0),
('Audio', 'Écouteurs Autres', '', 'Neuf', 1 , 0.0, 0.0),
('Audio', 'Casque JBL', '', 'Occasion', 1 , 0.0, 0.0),
('Audio', 'Micro Cravate', 'Avec fil', 'Neuf', 0 , 0.0, 0.0),
('Gaming', 'Manette', 'PC', 'Neuf', 2 , 0.0, 0.0),
('Gaming', 'Manette', 'PS2', 'Occasion', 1 , 0.0, 0.0),
('Gaming', 'Manette', 'PS3', 'Occasion', 4 , 0.0, 0.0),
('Gaming', 'Manette', 'PS4', 'Occasion', 0 , 0.0, 0.0),
('Gaming', 'Souris Gaming', '', 'Neuf', 1 , 0.0, 0.0),
('Multimédia', 'Télécommande', 'Canal+', 'Neuf', 0 , 0.0, 0.0),
('Multimédia', 'Télécommande', 'LED TV', 'Neuf', 4 , 0.0, 0.0),
('Multimédia', 'Télécommande', 'Digisat', 'Neuf', 4 , 0.0, 0.0),
('Multimédia', 'Télécommande', 'Universelle', 'Neuf', 2 , 0.0, 0.0),
('Multimédia', 'Télécommande', 'Grundig', 'Neuf', 3 , 0.0, 0.0),
('Multimédia', 'Télécommande', 'Hisense', 'Neuf', 0 , 0.0, 0.0),
('Multimédia', 'Télécommande', 'ND', 'Neuf', 0 , 0.0, 0.0),
('Multimédia', 'Combo TV', '', 'Occasion', 0 , 0.0, 0.0),
('Multimédia', 'Mort Carte Mémoire USB', 'PM', 'Neuf', 4 , 0.0, 0.0),
('Multimédia', 'Mort Carte Mémoire USB', 'GM', 'Neuf', 0 , 0.0, 0.0),
('Piles & Énergie', 'Pile CMOS', '2032', 'Neuf', 0 , 0.0, 0.0),
('Piles & Énergie', 'Pile CMOS', '2025', 'Neuf', 0 , 0.0, 0.0),
('Piles & Énergie', 'Pile 9V', '', 'Neuf', 19 , 0.0, 0.0),
('Piles & Énergie', 'Pile Bouton', 'LR44', 'Neuf', 5 , 0.0, 0.0),
('Piles & Énergie', 'Pile Bouton', 'LR1130', 'Neuf', 7 , 0.0, 0.0),
('Piles & Énergie', 'Pile Bouton', 'LR626', 'Neuf', 3 , 0.0, 0.0),
('Piles & Énergie', 'Pile Bouton', 'LR41W', 'Neuf', 8 , 0.0, 0.0),
('Piles & Énergie', 'Pile Bouton', 'LR62W', 'Neuf', 5 , 0.0, 0.0),
('Piles & Énergie', 'Pile Kodak/Toceba', '', 'Neuf', 0 , 0.0, 0.0),
('Piles & Énergie', 'Pile Duracell', 'GM', 'Neuf', 2 , 0.0, 0.0),
('Piles & Énergie', 'Pile Duracell', 'PM', 'Neuf', 0 , 0.0, 0.0),
('Piles & Énergie', 'Pile 10 éléments Vrac', 'PM', 'Neuf', 52 , 0.0, 0.0),
('Piles & Énergie', 'Pile 10 éléments Vrac', 'GM', 'Neuf', 7 , 0.0, 0.0),
('Batteries', 'Batterie iTel', '2500 mAh', 'Neuf', 0 , 0.0, 0.0),
('Batteries', 'Batterie iTel', '1500 mAh', 'Neuf', 0 , 0.0, 0.0),
('Batteries', 'Batterie iTel', '2580', 'Neuf', 2 , 0.0, 0.0),
('Batteries', 'Batterie Li-ion', '3.8V 12.16Wh', 'Neuf', 0 , 0.0, 0.0),
('Batteries', 'Batterie Tecno', 'Petite', 'Neuf', 0 , 0.0, 0.0),
('Batteries', 'Batterie Samsung', '', 'Neuf', 1 , 0.0, 0.0),
('Rallonges', 'Rallonge PowerMax', '', 'Neuf', 0 , 0.0, 0.0),
('Rallonges', 'Rallonge Simple', '3 prises', 'Neuf', 0 , 0.0, 0.0),
('Rallonges', 'Rallonge Simple', '4 prises', 'Neuf', 0 , 0.0, 0.0),
('Rallonges', 'Rallonge d''occasion', '3 prises', 'Occasion', 0 , 0.0, 0.0),
('Rallonges', 'Rallonge d''occasion', '4 prises', 'Occasion', 0 , 0.0, 0.0),
('Rallonges', 'Rallonge d''occasion', '6 prises', 'Occasion', 0 , 0.0, 0.0),
('Outils', 'Multimètre', '', 'Neuf', 8 , 0.0, 0.0);
